### ISSUE TITLE
Улетающие двери

### ISSUE THREAD

**Issue by vuvk** [vuvk/rgc_interpreter#1]
Исправить ошибку в скриптах горизонтального и вертикального движения. Ошибка следующая - иногда дверь выходит за положенную ей точку останова и продолжает движение. Возникает по той причине, что в скрипте проверяется расстояние до точки, а дверь может перелететь её и, оказавшись по иную сторону конечной координаты, начнёт расти расстояние до неё. И дверь улетает в никуда.
Прикладываю схему возникновения ошибки.
[https://s9.postimg.cc/69mfnbn7j/flying_doors.png](https://s9.postimg.cc/69mfnbn7j/flying_doors.png)

**Comment by dzanis** [comment]
https://github.com/dzanis/rgc_interpreter/commit/c4fb2e96d11c7d0b20f1fa27c79762200b3ee7e9
Потестировал изменения,больше двери не перелетали.
Как ветку к тебе к своему репо применить я пока не в курсе.

**Comment by vuvk** [comment]
Смержил. Если баг не проявится более, то закрою проблему. Там ещё второй скрипт с горизонтальным движением по образу и подобию

**Comment by vuvk** [comment]
Ничего не улетает. Гуд
