### ISSUE TITLE
Направление открывания поворотных дверей

### ISSUE THREAD

**Issue by vuvk** [vuvk/rgc_interpreter#10]
Обеспечить работу скрипта поворотных дверей при отрицательных значениях openSpeed

**Comment by dzanis** [comment]
Ничего если поворотные двери будут открываться только от игрока? Я думаю так будет удобнее.Нет смысла делать выбор открываться двери на себя или от себя,это же вообще ни на что не влияет,но зато раздражает застреванием когда дверь на игрока открывается.Вчера не смог решить,только сегодня с утра понял ошибку.

**Comment by vuvk** [comment]
Главное чтобы работали, а то начнут вращаться не в том направлении при минусовых значениях. Насчет застревания заметил. Нужно будет потом подшаманить такую же штуку, как в оригинальном Вольфе - пока дверь не открыта на весь блок стоит кубическая коллизия, когда дверь в открытом состоянии, то коллизию отключить

**Comment by dzanis** [comment]
Да,а то раздражает,ведь хочется побыстрому пробежать.А как на счёт выбора в редакторе чтоб дверь не закрывалась,это работает? Вспомнил,была такая дверь,работает.Реализовал,но очень костыльно,просто не хватает вектора направления игрока.

**Comment by vuvk** [comment]
Сейчас добавлю вектор взгляда

**Comment by dzanis** [comment]
lookAt?

**Comment by dzanis** [comment]
Получилось застрять в двери,подошёл когда дверь закрывалась и "застрял в текстурках" :)

**Comment by dzanis** [comment]
Я там так и не воспользовался вектором камеры,не осилил пока что.

**Comment by dzanis** [comment]
Я посмотрел,что если перенести проверку в `if (!needKey) {`  То может получится,но нажимать придётся два раза,один раз это использовать ключ,а второй раз уже дверь откроется.Вот появятся ключи,будет наглядней.

**Comment by dzanis** [comment]
Всё таки стоило бы ,обьединить все виды двери в один скрипт.Не сильно они отличаются.
Нужно в редакторе задать тип.
Вот по примеру из скрипта,короче и понятней будет.
```
const Type = {
    HORIZONTAL: 0,
    VERTICAL: 1,
    ROTATE: 2,
}
// получаем тип двери
var doorType = objectGetVar(doorId, "doorType");
```

**Comment by dzanis** [comment]
Да и скрипт не перезагружается при нажатии на "T" .Вносил изменения и ничего не происходит.

**Comment by vuvk** [comment]
"Всё таки стоило бы ,обьединить все виды двери в один скрипт" - не катит. Нужно для каждого поведения отдельный набор скриптов, а не кучу переменных в редакторе. Иначе теряется всякий смысл - проще уж было сразу в раннере всё поведение прописать.
Насчет перезагрузки скриптов - да, двери не перезагружаются почему-то, остальное гуд. Буду завтра разбираться что к чему.
