### ISSUE TITLE
Открывание дверей ключом

### ISSUE THREAD

**Issue by vuvk** [vuvk/rgc_interpreter#11]
Дополнить скрипты дверей проверкой о наличии у игрока необходимого ключа для её открывания. Использовать для этих целей переменную name у ключей и переменную keyName у дверей.

**Comment by dzanis** [comment]
Но сейчас на карте нет ключа и запертой двери.

**Comment by dzanis** [comment]
А у ключей не будет своего скрипта?

**Comment by vuvk** [comment]
будет простейший скрипт типа 
Если игрок на расстоянии меньше 0.2, то
добавить игроку булеву пременную с именем ключа
и удалить объект.

Кстати, надо добавить функцию удаления объекта в интерпретатор

**Comment by vuvk** [comment]
Залил версию с уже рабочими поворотными дверями с обработкой ключей. Осталось заставить работать остальные двери по такому же принципу.
Рестарт скриптовой машины работает. Как проверял: ткнул P, подменил скрипты дверей на другой тип, ткнул T - двери стали двигаться по-другому

**Comment by dzanis** [comment]
Всё таки мне что-то подсказывает, что  дверь больше не должна нуждаться в ключе,если её один раз открыть ключом.Получается если даже ключ потеряешь,дверь всё равно будет открыта.

```
                               if (!needKey) {
					startOpenDoor();
				}
				else {
					var keyName = objectGetVar(doorId, "keyName");
					var keyExists = objectGetVar(g_PlayerId, keyName);
					
					if (keyExists == true) {
	                                       objectSetVar(doorId, "needKey", false);
						startOpenDoor();
					}
					else {
						var message = objectGetVar(doorId, "message");
						print("Message: '" + message + "'");
					}
				}

```

**Comment by dzanis** [comment]
Да и ешё,сейчас это не так страшно.Но на всякий случай лучше учесть,потом неизвестно во что это превратит тест скриптов.В обшем если дверь открывается и перезапустить скрипты,дверь застывает на месте.

**Comment by vuvk** [comment]
> "дверь больше не должна нуждаться в ключе,если её один раз открыть ключом"

хорошая идея.

Перезапуск скриптов на то и перезапуск **только** скриптов - дверь выполняет то, что ей предписано. Чтобы при перезапуске всё вставало в нулевую позицию, надо пересоздавать все сущности (не реализовано). Или рестартить весь уровень.
