### ISSUE TITLE
Открыть закрывающуюся дверь при приближении игрока

### ISSUE THREAD

**Issue by vuvk** [vuvk/rgc_interpreter#16]
Если дверь начала закрываться, а игрок к ней приблизился, то дверь должна вернуться в открытое состояние

**Comment by dzanis** [comment]
А вот это будет наверное не просто

**Comment by dzanis** [comment]
Два вида двери легко дались.Но осталось с поворотной разобраться, у поворотной двери открывание с багом,если вернуться с другой стороны двери она "заклинивает".

**Comment by vuvk** [comment]
Всё работает. Отличная работа ;-)
