### ISSUE TITLE
Актуализировать скрипты для дверей

### ISSUE THREAD

**Issue by vuvk** [vuvk/rgc_interpreter#5]
Обновить скрипты вертикальных и поворотных дверей новыми функциями для работы с векторами. Как пример скрипты в assets/scripts/doors/hor

**Comment by dzanis** [comment]
Как освобожусь добавлю.Только вот бы двери на карту всех видов сразу.На данный момент есть только горизонтальные.

**Comment by vuvk** [comment]
Сейчас ещё нет возможности задавать скрипты из редактора и выполняются те, которые лежат в assets\scripts\doors\ для ВСЕХ дверей. Чтобы изменить тип на вертикальный, надо взять скрипты отсюда assets\scripts\doors\ver и положить с заменой в assets\scripts\doors\. Чтобы сделать двери поворотными, нужно взять скрипты отсюда assets\scripts\doors\rot и положить в assets\scripts\doors\

**Comment by vuvk** [comment]
в поворотном варианте остался старый кусок
`distToPlayer = (start.sub(g_PlayerPos)).length();`

**Comment by dzanis** [comment]
Вернул и переделал.Я проверял все скрипты,работают без проблем. С вертикальными дверями предлагаю добавить вариант открытия вверх или вниз.

**Comment by vuvk** [comment]
Впоследствии разделим на два варианта. Сейчас удобней писать в одном скрипте, нежели плодить их и в каждом править. Проверил - всё прекрасно работает. Спс.
Следующим шагом будет заставить двери работать по ключу. Как добавлю сущности ключей, дам знать.
Идея такая - двери будут проверять переменную у ИГРОКА с именем ключа, который необходим, чтобы открыть её. Когда игрок будет подбирать ключ, то у него будет появляться булеановская переменная с именем этого ключа.

**Comment by dzanis** [comment]
Не делить на два варианта а получить из раннера.Т.е это в самом редакторе установить кнопку в каком направлении открываться.Потом скриптом получить направление `var isMoveUp = getMoveTarget(doorId); `

**Comment by vuvk** [comment]
Ну, можно разрешить отрицательную скорость движения. И тогда немного поправить скрипт, чтоб движение двери менялось на обратное
