### ISSUE TITLE
Разное направление открывания дверей в зависимости от скорости

### ISSUE THREAD

**Issue by vuvk** [vuvk/rgc_interpreter#8]
Учесть в скриптах дверей, что скорость движения может быть отрицательной. При отрицательных значениях дверь должна двигаться в обратную сторону (вместо влево - двигается вправо, вместо вверх - двигается вниз).
Закоммитил новый тестовый уровень - в нем 4 двери, две с положительной скоростью, 2 с отрицательной, 2 вертикально расположенные на карте и 2 горизонтально

**Comment by dzanis** [comment]
Это сделаю.Теперь от отрицательной скорости дверь "уплывает" навсегда :)

**Comment by vuvk** [comment]
В том и задача - рассчитать точку end в зависимости от знака скорости. Завтра закончу с ключами - сейчас их можно настраивать в редакторе, но в раннера они не грузятся. Можешь уже сейчас "гипотетически" описать в поведении двери наличие ключа у игрока.

**Comment by dzanis** [comment]
Это решаю.Гипотетически не представляю.А может один ключ открыть много дверей? Например есть ключ от красных дверей,а красных дверей может быть несколько.  Да и с перезагрузкой по R ничего не вышло,потому что мышка застревает в центре,проще закрыть раннер.

**Comment by dzanis** [comment]
Горизонтальные и вертикальные решил.А с поворотной дверью у меня другая идея.

**Comment by vuvk** [comment]
Один ключ может открывать все двери, которым он установлен. Моя идея такая:
у ключа есть имя и идентификатор (name и keyId соответственно). Когда игрок подбирает ключ, то у него появляется флаг с именем ключа:
objectAddVarBool(g_PlayerId, name, true)
Дверям при создании будут заданы две переменных - keyName и keyId, которые нужно проверять, если выставлен флаг needKey.
Когда игрок пытается открыть дверь, требующую ключ, то проверяется есть ли у него такой флаг:
if (objectGetVar(g_PlayerId, keyName) == true) {}
Если у объекта нет запрашиваемой переменно (например, ключ ещё не взят), то objectGetVar возвращает 0

**Comment by dzanis** [comment]
Думаю что хватит просто текстового имя ключа. У двери должно быть имя и у ключа имя просто виде строки.
Т.е  в редакторе двери будет поле  keyName = "key1" (пользователь сможет легко на своё имя поменять).Такое же самое поле с keyName будет у ключа.Теперь можно будет одним ключом открыть хоть все двери у которых keyName  совпадёт. 
Теперь надо решить,сколько ключей носить с собой,если один то просто получить его в скрипте 
`var keyNameDoor = objectGetVar(doorId, "keyName ");`
А от игрока получить 
`var keyNamePlayer = objectGetVar(g_PlayerId, "keyName ");`
Дальше сравнил и открыл если одинаковы имена ключей.
`if(keyNameDoor  == keyNamePlayer)
.... `
Если можно будет носить несколько ключей,то придётся их в массив складывать.В скрипк массив передавать,немного больше писанины.

**Comment by vuvk** [comment]
Насчет удержания курсора мыши в центре - все в твоих руках. Можно сделать горячую клавишу и отключить центрирование в скрипте камеры

**Comment by vuvk** [comment]
Насчет нескольких ключей - не надо ничего складывать никуда. Есть ключ с именем "Key1", игрок к нему подошел и у него появилась переменная с этим именем objectAddVarBool(g_Player, "Key1", true);
Игрок подошел к двери где нужен Key1 и у него спрашивается - "а Key1 у тебя true??", если да, то открыть дверь. И так со всеми ключами

**Comment by dzanis** [comment]
Предлагаю добавить паузу,просто экран с надписью и освободить мышь,в паузе перезагружать скрипты нажатием на R ,и  опять запуск игры.Всёрано нужен будет выход в меню.Но сначала нужно убрать перезагрузку текстур, а то сёравно долго :)

**Comment by dzanis** [comment]
`objectAddVarBool(g_Player, "Key1", true);` так намного удобнее,извиняюсь не понял сразу.

**Comment by dzanis** [comment]
Подожди,но откуда скрипт то знает какое имя у ключа? Чёт не получается ничего,ведь так 
 `objectAddVarBool(g_Player, "Key1", true);` у всех ключей будет одно имя,т.е  "Key1"  хех

**Comment by dzanis** [comment]
Теперь понял
```
var keyName = objectGetVar(keyId, "keyName ");//ключ подобран,получаем имя ключа
objectAddVarBool(g_Player, keyName , true);//создаём плееру булевую с именем ключа
```

**Comment by vuvk** [comment]
У всех ключей есть имя - поле name (такое поле есть у всех сущностей). Именно с таким именем добавится переменная. У двери имя ключа в keyName. Для открытия двери ключом keyName нужно чтобы у игрока была переменная с таким же именем, как имя ключа == true.
Если не впетришь, то я завтра сам накидаю уже с ключами. Все равно новую задачу надо сделать в TODO
